language: python
python:
  - "3.7"
  - "3.8"
install:
  - pip3 install -r requirements.txt
  - pip3 install flake8
  - npm install
script:
  - flake8 .
  - ./node_modules/.bin/eslint static/scripts/script.js
